#resilience4j.circuitbreaker:
#  instances:
#    courseCatalog:
#      registerHealthIndicator: true
#      slidingWindowSize: 10
#      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowType: TIME_BASED
#      minimumNumberOfCalls: 20
#      waitDurationInOpenState: 50s
#      failureRateThreshold: 50
#      eventConsumerBufferSize: 10

#resilience4j:
#  circuitbreaker:
##    enabled: true
#    instances:
#      courseCatalogService:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED

resilience4j.circuitbreaker:
  instances:
    courseCatalogService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

management.health.circuitbreakers.enabled: true